import { Clock3, Mail, MapPin, Phone, ShieldCheck } from "lucide-react";
import { PageHero } from "@/components/page/PageHero";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
export function HeroSection(){return <PageHero eyebrow="Contact" title="Talk to a planner about your next route." description="Share your constraints and goals. We respond with a practical scope and recommended path." imageSrc="/assets/img/travel/misc-7.webp" imageAlt="Contact and support" />;}
export function ContactCardsSection(){return <section className="grid gap-4 lg:grid-cols-3"><Card><CardContent className="pt-6 text-sm"><Mail className="mb-1 size-5 text-primary" />hello@traveltime.com</CardContent></Card><Card><CardContent className="pt-6 text-sm"><Phone className="mb-1 size-5 text-primary" />+1 (555) 342-1188</CardContent></Card><Card><CardContent className="pt-6 text-sm"><MapPin className="mb-1 size-5 text-primary" />Los Angeles, CA</CardContent></Card></section>;}
export function ServiceLevelSection(){return <section className="rounded-2xl border bg-card p-4 sm:p-6"><h2 className="mb-3 text-xl font-semibold">Service levels</h2><div className="grid gap-3 sm:grid-cols-3 text-sm"><div className="rounded-lg border p-3"><Clock3 className="mb-2 size-4 text-primary" />General response: within 18 minutes</div><div className="rounded-lg border p-3"><Badge>Priority</Badge><p className="mt-2">In-trip support escalation available</p></div><div className="rounded-lg border p-3"><ShieldCheck className="mb-2 size-4 text-primary" />Secure handling of traveler data</div></div></section>;}
export function FormSection(){return <section className="grid gap-4 lg:grid-cols-2"><img src="/assets/img/travel/misc-3.webp" alt="Customer support" className="h-56 w-full rounded-2xl border object-cover sm:h-72 lg:h-full" loading="lazy" /><Card><CardHeader><CardTitle>Send a message</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2"><Input placeholder="Name" /><Input type="email" placeholder="Email" /><Input className="md:col-span-2" placeholder="Subject" /><div className="md:col-span-2"><Textarea placeholder="Your message" /></div><div><Button>Send</Button></div></CardContent></Card></section>;}
